"""Interactive dashboard for the Lab 17 memory agent.

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
import time
from html import escape
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, estimate_tokens, load_dataset, load_json, normalize
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CSS = """
<style>
.stApp { background:#f4f6f8; color:#18212b; }
.block-container { padding-top:1.4rem; padding-bottom:3rem; max-width:1380px; }
[data-testid="stSidebar"] { background:#17202a; border-right:1px solid #2f3b47; }
[data-testid="stSidebar"] * { color:#f5f7f9; }
[data-testid="stSidebar"] .stSelectbox div[data-baseweb="select"] > div {
    background:#25313d; border-color:#3b4a59;
}
h1, h2, h3 { letter-spacing:0; }
.app-header { display:flex; align-items:flex-start; justify-content:space-between; gap:24px; margin-bottom:18px; }
.app-title { font-size:1.75rem; line-height:1.15; font-weight:750; margin:0; color:#101820; }
.app-subtitle { margin-top:6px; color:#5c6975; font-size:.93rem; }
.status-row { display:flex; gap:8px; flex-wrap:wrap; justify-content:flex-end; }
.status-pill { display:inline-flex; align-items:center; gap:7px; border:1px solid #d5dce2;
    background:#fff; padding:7px 10px; border-radius:6px; font-size:.78rem; font-weight:650; }
.status-dot { width:8px; height:8px; border-radius:50%; background:#159455; }
.status-dot.off { background:#c4423a; }
.lab-badge {
    display:inline-block; padding:3px 9px; border-radius:5px;
    color:#fff; font-size:0.72rem; font-weight:700; letter-spacing:0;
    margin-right:6px;
}
.case-panel { border:1px solid #d5dce2; border-left:4px solid #2563eb; border-radius:7px;
    padding:16px 18px; margin-bottom:14px; background:#fff; box-shadow:0 1px 2px rgba(16,24,32,.04); }
.case-top { display:flex; align-items:center; justify-content:space-between; gap:12px; }
.case-id { font-size:1rem; font-weight:750; }
.case-query { font-size:1.05rem; line-height:1.55; margin:12px 0 6px; color:#18212b; }
.case-description { color:#66737f; font-size:.84rem; }
.case-meta { color:#596672; font-size:.78rem; font-family:ui-monospace, SFMono-Regular, Menlo, monospace; }
.result-strip { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:10px; margin:8px 0 14px; }
.result-cell { border:1px solid #d5dce2; background:#fff; border-radius:7px; padding:12px 13px; min-height:76px; }
.result-label { color:#6a7681; font-size:.72rem; text-transform:uppercase; font-weight:700; }
.result-value { color:#18212b; font-size:1.08rem; font-weight:750; margin-top:5px; overflow-wrap:anywhere; }
.result-value.pass { color:#087a43; }
.result-value.fail { color:#b3312b; }
.budget-track { height:5px; background:#e7ebef; border-radius:3px; overflow:hidden; margin-top:8px; }
.budget-fill { height:100%; border-radius:3px; }
.budget-meta { color:#74808a; font-size:.7rem; margin-top:6px; }
.empty-state { border:1px dashed #b9c2ca; border-radius:7px; background:#fff; padding:42px 24px;
    color:#64717c; text-align:center; }
.evidence-box { border:1px solid #d5dce2; background:#fff; border-radius:7px; padding:14px;
    max-height:440px; overflow:auto; white-space:pre-wrap; font-family:ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size:.78rem; line-height:1.55; color:#26323d; }
.marker-list { display:flex; flex-wrap:wrap; gap:6px; margin-top:9px; }
.marker { border:1px solid #cfd7de; background:#f7f9fa; border-radius:5px; padding:3px 7px; font-size:.72rem; }
.marker.hit { border-color:#99cfb4; background:#eef8f2; color:#087a43; }
.marker.miss { border-color:#e3aaa6; background:#fff2f1; color:#a92d27; }
.sidebar-brand { font-weight:750; font-size:1.02rem; margin-bottom:4px; }
.sidebar-copy { color:#b9c3cc !important; font-size:.78rem; line-height:1.45; margin-bottom:18px; }
.stButton > button { border-radius:6px; font-weight:700; min-height:42px; }
.stButton > button[kind="primary"] { background:#16734b; border-color:#16734b; }
.stButton > button[kind="primary"]:hover { background:#105e3d; border-color:#105e3d; }
[data-testid="stMetric"] { border:1px solid #d5dce2; background:#fff; padding:10px 12px; border-radius:7px; }
[data-testid="stChatMessage"] { border:1px solid #d5dce2; background:#fff; border-radius:7px; }
@media (max-width: 800px) {
    .app-header { display:block; }
    .status-row { justify-content:flex-start; margin-top:12px; }
    .result-strip { grid-template-columns:repeat(2,minmax(0,1fr)); }
    .case-top { display:block; }
}
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Retrieve all selected memory layers for a dataset case."""
    dataset = load_dataset()
    layers = {"short_term": "", "long_term": "", "episodic": "", "semantic": ""}

    messages = case.get("fixture_messages")
    if messages is None:
        messages = []
        user = next(
            (item for item in dataset["users"] if item["user_id"] == case["user_id"]),
            None,
        )
        if user:
            session = next(
                (item for item in user.get("sessions", []) if item["thread_id"] == case["thread_id"]),
                None,
            )
            messages = list((session or {}).get("messages", []))

    selected = case.get("retrieve_layers")
    if not selected:
        expected = case.get("expected_layer", "mixed")
        selected = [expected] if expected != "mixed" else ["long_term", "semantic"]

    if "short_term" in selected or messages or extra_messages:
        short_term = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
        for message in [*messages, *extra_messages]:
            short_term.add(message["role"], message["content"])
        layers["short_term"] = short_term.render()
    if "long_term" in selected:
        layers["long_term"] = memory.retrieve_long_term(
            case["user_id"], case["thread_id"], case["query"]
        )
    if "episodic" in selected:
        layers["episodic"] = memory.retrieve_episodic(case["user_id"], case["query"])
    if "semantic" in selected:
        layers["semantic"] = memory.retrieve_semantic(
            settings.semantic_graph_id, case["query"]
        )

    merged_context, budget = memory.assemble_context(layers)
    return {"merged_context": merged_context, "layers": layers, "budget": budget}


def score_result(case: dict[str, Any], text: str) -> tuple[bool, list[str], list[str]]:
    normalized = normalize(text)
    missing = [item for item in case.get("must_contain_all", []) if normalize(item) not in normalized]
    forbidden = [item for item in case.get("must_not_contain", []) if normalize(item) in normalized]
    return not missing and not forbidden, missing, forbidden


def render_budget_cards(result: dict[str, Any]) -> None:
    cards = []
    for layer in ("short_term", "long_term", "episodic", "semantic"):
        item = result.get("budget", {}).get(layer, {})
        used = item.get("used_tokens", 0)
        limit = max(1, item.get("limit_tokens", 0))
        percent = min(100, round(used / limit * 100))
        cards.append(
            '<div class="result-cell">'
            f'<div class="result-label">{escape(layer.replace("_", " "))}</div>'
            f'<div class="result-value">{used} <span style="font-size:.72rem;color:#78838d">tokens</span></div>'
            f'<div class="budget-track"><div class="budget-fill" style="width:{percent}%;background:{LAYER_COLORS[layer]}"></div></div>'
            f'<div class="budget-meta">{percent}% of {limit} token limit</div>'
            '</div>'
        )
    st.markdown('<div class="result-strip">' + "".join(cards) + '</div>', unsafe_allow_html=True)


def main() -> None:
    st.set_page_config(page_title="Memory Inspector", page_icon="M", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)

    with st.sidebar:
        st.markdown('<div class="sidebar-brand">Memory Inspector</div>', unsafe_allow_html=True)
        st.markdown(
            '<div class="sidebar-copy">Inspect retrieval across working, user, episodic and shared semantic memory.</div>',
            unsafe_allow_html=True,
        )
        st.caption("EVALUATION CASE")
        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Evaluation case", labels, label_visibility="collapsed")
        case = cases[labels.index(chosen)]
        st.divider()
        st.caption("CASE DETAILS")
        st.markdown(f"**Layer:** `{case.get('expected_layer', '-')}`")
        st.markdown(f"**User:** `{case.get('user_id', '-')}`")
        st.markdown(f"**Thread:** `{case.get('thread_id', '-')}`")
        st.markdown(f"**Stage:** `{case.get('after_stage', '-')}`")
        st.divider()
        if st.button("Clear conversation", use_container_width=True):
            st.session_state.chat = []
            st.session_state.pop("last_result", None)
            st.rerun()

    zep_ok = bool(settings.zep_api_key)
    gemini_ok = gemini_available()
    st.markdown(
        '<div class="app-header"><div>'
        '<div class="app-title">Multi-memory retrieval console</div>'
        '<div class="app-subtitle">Trace evidence, validate ground truth and continue the conversation.</div>'
        '</div><div class="status-row">'
        f'<div class="status-pill"><span class="status-dot{"" if zep_ok else " off"}"></span>Zep {"connected" if zep_ok else "not configured"}</div>'
        f'<div class="status-pill"><span class="status-dot{"" if gemini_ok else " off"}"></span>Gemini {"ready" if gemini_ok else "optional"}</div>'
        '</div></div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="case-panel"><div class="case-top"><div>'
        f'{layer_badge(case.get("expected_layer", "?"))}<span class="case-id">{escape(case["id"])}</span>'
        f'</div><div class="case-meta">{escape(case.get("user_id", "-"))} / {escape(case.get("thread_id", "-"))}</div></div>'
        f'<div class="case-query">{escape(case.get("query", ""))}</div>'
        f'<div class="case-description">{escape(case.get("description", ""))}</div>'
        '</div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    run_col, meta_col = st.columns([1, 3])
    if run_col.button("Run retrieval", type="primary", use_container_width=True):
        try:
            with st.spinner("Retrieving memory layers..."):
                started = time.perf_counter()
                memory = StudentMemory(get_zep_client())
                result = retrieve_for_case(memory, case, st.session_state.chat)
                result["latency_ms"] = round((time.perf_counter() - started) * 1000, 1)
                st.session_state.last_result = result
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)
    meta_col.caption("Retrieval is deterministic; Gemini is only used for the conversational reply.")

    result = st.session_state.get("last_result")
    inspector_col, chat_col = st.columns([1.45, 1], gap="large")
    with inspector_col:
        st.subheader("Retrieval inspector")
        if not result:
            st.markdown(
                '<div class="empty-state"><b>No retrieval run yet</b><br><span>Run the selected case to inspect its evidence and token budget.</span></div>',
                unsafe_allow_html=True,
            )
        else:
            merged = result.get("merged_context", "")
            passed, missing, forbidden = score_result(case, merged)
            active = [name for name, text in result["layers"].items() if text.strip()]
            st.markdown(
                '<div class="result-strip">'
                f'<div class="result-cell"><div class="result-label">Ground truth</div><div class="result-value {"pass" if passed else "fail"}">{"PASS" if passed else "FAIL"}</div></div>'
                f'<div class="result-cell"><div class="result-label">Latency</div><div class="result-value">{result.get("latency_ms", 0):.1f} ms</div></div>'
                f'<div class="result-cell"><div class="result-label">Context size</div><div class="result-value">{estimate_tokens(merged)} tokens</div></div>'
                f'<div class="result-cell"><div class="result-label">Active layers</div><div class="result-value">{len(active)} / 4</div></div>'
                '</div>',
                unsafe_allow_html=True,
            )
            render_budget_cards(result)
            marker_html = []
            for marker in case.get("must_contain_all", []):
                hit = normalize(marker) in normalize(merged)
                marker_html.append(f'<span class="marker {"hit" if hit else "miss"}">{escape(marker)}</span>')
            for marker in forbidden:
                marker_html.append(f'<span class="marker miss">forbidden: {escape(marker)}</span>')
            if marker_html:
                st.markdown('<div class="marker-list">' + "".join(marker_html) + '</div>', unsafe_allow_html=True)
            if missing:
                st.caption("Missing evidence: " + ", ".join(missing))

            tabs = st.tabs(["Merged context", "Short-term", "Long-term", "Episodic", "Semantic"])
            tab_values = [merged] + [
                result["layers"].get(name, "")
                for name in ("short_term", "long_term", "episodic", "semantic")
            ]
            for tab, text in zip(tabs, tab_values, strict=True):
                with tab:
                    st.markdown(
                        f'<div class="evidence-box">{escape(text or "No evidence retrieved for this layer.")}</div>',
                        unsafe_allow_html=True,
                    )

    with chat_col:
        st.subheader("Conversation")
        st.caption(f"Continuing as `{case.get('user_id')}` in `{case.get('thread_id')}`")
        chat_messages = st.session_state.get("chat", [])
        if not chat_messages:
            st.info("Ask a follow-up question after running retrieval. The reply will be grounded in the same memory context.")
        for msg in chat_messages:
            with st.chat_message(msg["role"]):
                st.write(msg["content"])

    prompt = st.chat_input("Ask a follow-up question using this user's memory")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if gemini_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(Gemini key missing — showing retrieved context instead)_\n\n"
                         + (context[:1500] or "(no memory retrieved)"))
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
